platform:ios,'8.0'
target:LSOperationTools do

  pod 'LSCommonality','~> 0.0.13'
  
  pod 'LSMiddleWare','~> 0.0.4'
  
  # 集成微信(精简版0.2M)
  pod 'UMengUShare/Social/ReducedWeChat'
  
  # 集成QQ/QZone/TIM(精简版0.5M)
  pod 'UMengUShare/Social/ReducedQQ'
  
  # 集成新浪微博(精简版1M)
  pod 'UMengUShare/Social/ReducedSina'
  
  # 极光推送
  pod 'JPush', '3.1.0'

end
